2023-12-25 18:50:43 WARNING [dao.py::87] No response was returned from database call {'query': 'select * from py201_cart where `userId`=%s and `productId`=%s'}
2023-12-25 18:50:43 ERROR [dao.py::111] Failed to get cart item {'query': 'insert into py201_cart (`userId`, `productId`, `count`) values (%s, %s, %s)', 'err': '1264 (22003): target: maindb.-.primary: vttablet: Out of range value for column \'productId\' at row 1 (errno 1264) (sqlstate 22003) (CallerID: 9smxynsgmtbkhjqzzjgs): Sql: "insert into py201_cart(userId, productId, `count`) values (:vtg1 /* VARCHAR */, 13215102657288470000, :vtg2 /* INT64 */)", BindVars: {REDACTED}'}
2023-12-25 18:55:40 WARNING [dao.py::87] No response was returned from database call {'query': 'select * from py201_cart where `userId`=%s and `productId`=%s'}
2023-12-25 18:55:40 ERROR [dao.py::111] Failed to get cart item {'query': 'insert into py201_cart (`userId`, `productId`, `count`) values (%s, %s, %s)', 'err': '1264 (22003): target: maindb.-.primary: vttablet: Out of range value for column \'productId\' at row 1 (errno 1264) (sqlstate 22003) (CallerID: 9smxynsgmtbkhjqzzjgs): Sql: "insert into py201_cart(userId, productId, `count`) values (:vtg1 /* VARCHAR */, :vtg2 /* VARCHAR */, :vtg3 /* INT64 */)", BindVars: {REDACTED}'}
2023-12-25 19:00:20 WARNING [dao.py::87] No response was returned from database call {'query': 'select * from py201_cart where `userId`=%s and `productId`=%s'}
2023-12-25 19:01:37 WARNING [dao.py::87] No response was returned from database call {'query': 'select * from py201_cart where `userId`=%s and `productId`=%s'}
